### ISSUE TITLE
Acquire Images for Training

### ISSUE THREAD

**Issue by cfloquetcapstone** [cfloquetcapstone/CCC-410-Capstone-Design#5]
### Overview:
I will need to take about 10-20 pictures of each brick I want to sort, but hopefully I will be able to tie in some of the open sourced Lego Imaging projects online and pre-process them (which will be a different issue). 

### Tasks:
- [x] Acquire Working CanaKit 8MP Camera for Raspberry Pi 3
- [ ] Verify Working Camera 
- [ ] Pictures taken for atleast 10-20 bricks for initial training purposes
