### ISSUE TITLE
Develop Pre-Processing Script

### ISSUE THREAD

**Issue by cfloquetcapstone** [cfloquetcapstone/CCC-410-Capstone-Design#6]
### Overview:
Since I will likely be bolstering the training image set with images taken from open source projects online, I will need to make all of the images (regardless of quality or background) to be consistent when processed and stored by the ML algorithm. 

### Tasks:
- [x] Create anaconda 'PreProc' environment using Python 3.7
- [x] Install requisite MatPlotLib libraries
- [x] Install Scikit-Learn Libraries
- [x] Install opencv for image processing
- [x] Install tqdm
- [x] Test os file directory interaction
- [x] Reshape all images to same dimensions 
- [x]  Pass Images to Grayscale
- [x] Covert all images to an array
- [x]  Save the training data externally for easy access by neural network.

**Comment by cfloquetcapstone** [comment]
I've installed MPL Toolkit as well as Scikit learn. I think I will need the "Axes3D" module for plotting the image data accurately, which will take place after all of the preprocessing, and also Standard scaler works as a consistency mechanism used as a requisite by a ton of ML algorithms to standardize their data. 
I've also created a new python environment to install both of these called "PreProc".
